blank_issues_enabled: true
contact_links:
  - name: 🙌 Just shout it out
    url: https://github.com/MohakBajaj/build-2026-cli-live
    about: Not sure what to file? No worries — shout your idea out loud when we ask.
